name: github action tigger practices
on:
  push: 
  branches:
    -main
  pull_request: 
   branches: 
     -devlop
     -main
   
jobs:
  first_job:
    name: first job
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello world"
  
